name: Create Docker image of new release
on:
  schedule:
    - cron:  '0 8 * * SUN'
  workflow_dispatch:
jobs:
  check-for-release:
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: skylot/jadx
          releases-only: true
        id: jadx-tag

      - uses: oprypin/find-latest-tag@v1
        with:
          repository: bugautomationplatform/jadx-docker
          releases-only: true
        id: jadx-docker-tag 
    outputs:
      new-release: ${{ steps.jadx-tag.outputs.tag != steps.jadx-docker-tag.outputs.tag }}
      release-tag: ${{ steps.jadx-tag.outputs.tag }}
  
  release:
    needs: [check-for-release]
    if: ${{ needs.check-for-release.outputs.new-release == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: bugautomationplatform/jadx:${{ needs.check-for-release.outputs.release-tag }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.check-for-release.outputs.release-tag }}
          body: |
            bugautomationplatform/jadx:${{ needs.check-for-release.outputs.release-tag }}
            https://hub.docker.com/r/bugautomationplatform/jadx